//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 04:18:37 PM SGT 
//


package it.illinois.adsc.ema.control.cid;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.illinois.adsc.ema.control.cid package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SCL_QNAME = new QName("http://www.iec.ch/61850/2003/SCL", "SCL");
    private final static QName _LNTypeDOI_QNAME = new QName("http://www.iec.ch/61850/2003/SCL", "DOI");
    private final static QName _DATypeVal_QNAME = new QName("http://www.iec.ch/61850/2003/SCL", "Val");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.illinois.adsc.ema.control.cid
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SCLType }
     * 
     */
    public SCLType createSCLType() {
        return new SCLType();
    }

    /**
     * Create an instance of {@link SubNetworkType }
     * 
     */
    public SubNetworkType createSubNetworkType() {
        return new SubNetworkType();
    }

    /**
     * Create an instance of {@link OptFieldsType }
     * 
     */
    public OptFieldsType createOptFieldsType() {
        return new OptFieldsType();
    }

    /**
     * Create an instance of {@link ServerType }
     * 
     */
    public ServerType createServerType() {
        return new ServerType();
    }

    /**
     * Create an instance of {@link DynDataSetType }
     * 
     */
    public DynDataSetType createDynDataSetType() {
        return new DynDataSetType();
    }

    /**
     * Create an instance of {@link DataTypeTemplatesType }
     * 
     */
    public DataTypeTemplatesType createDataTypeTemplatesType() {
        return new DataTypeTemplatesType();
    }

    /**
     * Create an instance of {@link ConfLNsType }
     * 
     */
    public ConfLNsType createConfLNsType() {
        return new ConfLNsType();
    }

    /**
     * Create an instance of {@link LN0Type }
     * 
     */
    public LN0Type createLN0Type() {
        return new LN0Type();
    }

    /**
     * Create an instance of {@link LNodeTypeType }
     * 
     */
    public LNodeTypeType createLNodeTypeType() {
        return new LNodeTypeType();
    }

    /**
     * Create an instance of {@link IEDType }
     * 
     */
    public IEDType createIEDType() {
        return new IEDType();
    }

    /**
     * Create an instance of {@link ReportSettingsType }
     * 
     */
    public ReportSettingsType createReportSettingsType() {
        return new ReportSettingsType();
    }

    /**
     * Create an instance of {@link ConfLogControlType }
     * 
     */
    public ConfLogControlType createConfLogControlType() {
        return new ConfLogControlType();
    }

    /**
     * Create an instance of {@link EnumValType }
     * 
     */
    public EnumValType createEnumValType() {
        return new EnumValType();
    }

    /**
     * Create an instance of {@link FCDAType }
     * 
     */
    public FCDAType createFCDAType() {
        return new FCDAType();
    }

    /**
     * Create an instance of {@link TrgOpsType }
     * 
     */
    public TrgOpsType createTrgOpsType() {
        return new TrgOpsType();
    }

    /**
     * Create an instance of {@link ConfDataSetType }
     * 
     */
    public ConfDataSetType createConfDataSetType() {
        return new ConfDataSetType();
    }

    /**
     * Create an instance of {@link ConfReportControlType }
     * 
     */
    public ConfReportControlType createConfReportControlType() {
        return new ConfReportControlType();
    }

    /**
     * Create an instance of {@link DAType }
     * 
     */
    public DAType createDAType() {
        return new DAType();
    }

    /**
     * Create an instance of {@link DOTypeType }
     * 
     */
    public DOTypeType createDOTypeType() {
        return new DOTypeType();
    }

    /**
     * Create an instance of {@link ServicesType }
     * 
     */
    public ServicesType createServicesType() {
        return new ServicesType();
    }

    /**
     * Create an instance of {@link BitRateType }
     * 
     */
    public BitRateType createBitRateType() {
        return new BitRateType();
    }

    /**
     * Create an instance of {@link LDeviceType }
     * 
     */
    public LDeviceType createLDeviceType() {
        return new LDeviceType();
    }

    /**
     * Create an instance of {@link HitemType }
     * 
     */
    public HitemType createHitemType() {
        return new HitemType();
    }

    /**
     * Create an instance of {@link VoltageLevelType }
     * 
     */
    public VoltageLevelType createVoltageLevelType() {
        return new VoltageLevelType();
    }

    /**
     * Create an instance of {@link DOIType }
     * 
     */
    public DOIType createDOIType() {
        return new DOIType();
    }

    /**
     * Create an instance of {@link DATypeType }
     * 
     */
    public DATypeType createDATypeType() {
        return new DATypeType();
    }

    /**
     * Create an instance of {@link AuthenticationType }
     * 
     */
    public AuthenticationType createAuthenticationType() {
        return new AuthenticationType();
    }

    /**
     * Create an instance of {@link ReportControlType }
     * 
     */
    public ReportControlType createReportControlType() {
        return new ReportControlType();
    }

    /**
     * Create an instance of {@link DataSetType }
     * 
     */
    public DataSetType createDataSetType() {
        return new DataSetType();
    }

    /**
     * Create an instance of {@link PType }
     * 
     */
    public PType createPType() {
        return new PType();
    }

    /**
     * Create an instance of {@link BayType }
     * 
     */
    public BayType createBayType() {
        return new BayType();
    }

    /**
     * Create an instance of {@link SDIType }
     * 
     */
    public SDIType createSDIType() {
        return new SDIType();
    }

    /**
     * Create an instance of {@link HistoryType }
     * 
     */
    public HistoryType createHistoryType() {
        return new HistoryType();
    }

    /**
     * Create an instance of {@link LogSettingsType }
     * 
     */
    public LogSettingsType createLogSettingsType() {
        return new LogSettingsType();
    }

    /**
     * Create an instance of {@link AccessPointType }
     * 
     */
    public AccessPointType createAccessPointType() {
        return new AccessPointType();
    }

    /**
     * Create an instance of {@link ConnectedAPType }
     * 
     */
    public ConnectedAPType createConnectedAPType() {
        return new ConnectedAPType();
    }

    /**
     * Create an instance of {@link CommunicationType }
     * 
     */
    public CommunicationType createCommunicationType() {
        return new CommunicationType();
    }

    /**
     * Create an instance of {@link DOType }
     * 
     */
    public DOType createDOType() {
        return new DOType();
    }

    /**
     * Create an instance of {@link EnumTypeType }
     * 
     */
    public EnumTypeType createEnumTypeType() {
        return new EnumTypeType();
    }

    /**
     * Create an instance of {@link RptEnabledType }
     * 
     */
    public RptEnabledType createRptEnabledType() {
        return new RptEnabledType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link DAIType }
     * 
     */
    public DAIType createDAIType() {
        return new DAIType();
    }

    /**
     * Create an instance of {@link BDAType }
     * 
     */
    public BDAType createBDAType() {
        return new BDAType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link SubstationType }
     * 
     */
    public SubstationType createSubstationType() {
        return new SubstationType();
    }

    /**
     * Create an instance of {@link LNType }
     * 
     */
    public LNType createLNType() {
        return new LNType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SCLType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iec.ch/61850/2003/SCL", name = "SCL")
    public JAXBElement<SCLType> createSCL(SCLType value) {
        return new JAXBElement<SCLType>(_SCL_QNAME, SCLType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DOIType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iec.ch/61850/2003/SCL", name = "DOI", scope = LNType.class)
    public JAXBElement<DOIType> createLNTypeDOI(DOIType value) {
        return new JAXBElement<DOIType>(_LNTypeDOI_QNAME, DOIType.class, LNType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iec.ch/61850/2003/SCL", name = "Val", scope = DAType.class)
    public JAXBElement<String> createDATypeVal(String value) {
        return new JAXBElement<String>(_DATypeVal_QNAME, String.class, DAType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iec.ch/61850/2003/SCL", name = "Val", scope = DAIType.class)
    public JAXBElement<String> createDAITypeVal(String value) {
        return new JAXBElement<String>(_DATypeVal_QNAME, String.class, DAIType.class, value);
    }

}
