//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 04:18:37 PM SGT 
//


package it.illinois.adsc.ema.control.cid;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DynAssociation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GetDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GetDataObjectDefinition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataObjectDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GetDataSetValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataSetDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ConfDataSet" type="{http://www.iec.ch/61850/2003/SCL}ConfDataSetType"/>
 *         &lt;element name="DynDataSet" type="{http://www.iec.ch/61850/2003/SCL}DynDataSetType"/>
 *         &lt;element name="ReadWrite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ConfReportControl" type="{http://www.iec.ch/61850/2003/SCL}ConfReportControlType"/>
 *         &lt;element name="GetCBValues" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportSettings" type="{http://www.iec.ch/61850/2003/SCL}ReportSettingsType"/>
 *         &lt;element name="LogSettings" type="{http://www.iec.ch/61850/2003/SCL}LogSettingsType"/>
 *         &lt;element name="ConfLogControl" type="{http://www.iec.ch/61850/2003/SCL}ConfLogControlType"/>
 *         &lt;element name="FileHandling" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ConfLNs" type="{http://www.iec.ch/61850/2003/SCL}ConfLNsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServicesType", namespace = "http://www.iec.ch/61850/2003/SCL", propOrder = {
    "dynAssociation",
    "getDirectory",
    "getDataObjectDefinition",
    "dataObjectDirectory",
    "getDataSetValue",
    "dataSetDirectory",
    "confDataSet",
    "dynDataSet",
    "readWrite",
    "confReportControl",
    "getCBValues",
    "reportSettings",
    "logSettings",
    "confLogControl",
    "fileHandling",
    "confLNs"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class ServicesType {

    @XmlElement(name = "DynAssociation", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String dynAssociation;
    @XmlElement(name = "GetDirectory", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String getDirectory;
    @XmlElement(name = "GetDataObjectDefinition", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String getDataObjectDefinition;
    @XmlElement(name = "DataObjectDirectory", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String dataObjectDirectory;
    @XmlElement(name = "GetDataSetValue", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String getDataSetValue;
    @XmlElement(name = "DataSetDirectory", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String dataSetDirectory;
    @XmlElement(name = "ConfDataSet", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ConfDataSetType confDataSet;
    @XmlElement(name = "DynDataSet", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected DynDataSetType dynDataSet;
    @XmlElement(name = "ReadWrite", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String readWrite;
    @XmlElement(name = "ConfReportControl", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ConfReportControlType confReportControl;
    @XmlElement(name = "GetCBValues", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String getCBValues;
    @XmlElement(name = "ReportSettings", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ReportSettingsType reportSettings;
    @XmlElement(name = "LogSettings", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected LogSettingsType logSettings;
    @XmlElement(name = "ConfLogControl", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ConfLogControlType confLogControl;
    @XmlElement(name = "FileHandling", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String fileHandling;
    @XmlElement(name = "ConfLNs", namespace = "http://www.iec.ch/61850/2003/SCL", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ConfLNsType confLNs;

    /**
     * Gets the value of the dynAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getDynAssociation() {
        return dynAssociation;
    }

    /**
     * Sets the value of the dynAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDynAssociation(String value) {
        this.dynAssociation = value;
    }

    /**
     * Gets the value of the getDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getGetDirectory() {
        return getDirectory;
    }

    /**
     * Sets the value of the getDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setGetDirectory(String value) {
        this.getDirectory = value;
    }

    /**
     * Gets the value of the getDataObjectDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getGetDataObjectDefinition() {
        return getDataObjectDefinition;
    }

    /**
     * Sets the value of the getDataObjectDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setGetDataObjectDefinition(String value) {
        this.getDataObjectDefinition = value;
    }

    /**
     * Gets the value of the dataObjectDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getDataObjectDirectory() {
        return dataObjectDirectory;
    }

    /**
     * Sets the value of the dataObjectDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDataObjectDirectory(String value) {
        this.dataObjectDirectory = value;
    }

    /**
     * Gets the value of the getDataSetValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getGetDataSetValue() {
        return getDataSetValue;
    }

    /**
     * Sets the value of the getDataSetValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setGetDataSetValue(String value) {
        this.getDataSetValue = value;
    }

    /**
     * Gets the value of the dataSetDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getDataSetDirectory() {
        return dataSetDirectory;
    }

    /**
     * Sets the value of the dataSetDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDataSetDirectory(String value) {
        this.dataSetDirectory = value;
    }

    /**
     * Gets the value of the confDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link ConfDataSetType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ConfDataSetType getConfDataSet() {
        return confDataSet;
    }

    /**
     * Sets the value of the confDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfDataSetType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setConfDataSet(ConfDataSetType value) {
        this.confDataSet = value;
    }

    /**
     * Gets the value of the dynDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link DynDataSetType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public DynDataSetType getDynDataSet() {
        return dynDataSet;
    }

    /**
     * Sets the value of the dynDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynDataSetType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDynDataSet(DynDataSetType value) {
        this.dynDataSet = value;
    }

    /**
     * Gets the value of the readWrite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getReadWrite() {
        return readWrite;
    }

    /**
     * Sets the value of the readWrite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setReadWrite(String value) {
        this.readWrite = value;
    }

    /**
     * Gets the value of the confReportControl property.
     * 
     * @return
     *     possible object is
     *     {@link ConfReportControlType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ConfReportControlType getConfReportControl() {
        return confReportControl;
    }

    /**
     * Sets the value of the confReportControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfReportControlType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setConfReportControl(ConfReportControlType value) {
        this.confReportControl = value;
    }

    /**
     * Gets the value of the getCBValues property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getGetCBValues() {
        return getCBValues;
    }

    /**
     * Sets the value of the getCBValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setGetCBValues(String value) {
        this.getCBValues = value;
    }

    /**
     * Gets the value of the reportSettings property.
     * 
     * @return
     *     possible object is
     *     {@link ReportSettingsType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ReportSettingsType getReportSettings() {
        return reportSettings;
    }

    /**
     * Sets the value of the reportSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportSettingsType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setReportSettings(ReportSettingsType value) {
        this.reportSettings = value;
    }

    /**
     * Gets the value of the logSettings property.
     * 
     * @return
     *     possible object is
     *     {@link LogSettingsType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public LogSettingsType getLogSettings() {
        return logSettings;
    }

    /**
     * Sets the value of the logSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogSettingsType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setLogSettings(LogSettingsType value) {
        this.logSettings = value;
    }

    /**
     * Gets the value of the confLogControl property.
     * 
     * @return
     *     possible object is
     *     {@link ConfLogControlType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ConfLogControlType getConfLogControl() {
        return confLogControl;
    }

    /**
     * Sets the value of the confLogControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfLogControlType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setConfLogControl(ConfLogControlType value) {
        this.confLogControl = value;
    }

    /**
     * Gets the value of the fileHandling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getFileHandling() {
        return fileHandling;
    }

    /**
     * Sets the value of the fileHandling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setFileHandling(String value) {
        this.fileHandling = value;
    }

    /**
     * Gets the value of the confLNs property.
     * 
     * @return
     *     possible object is
     *     {@link ConfLNsType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ConfLNsType getConfLNs() {
        return confLNs;
    }

    /**
     * Sets the value of the confLNs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfLNsType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-10-24T04:18:37+08:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setConfLNs(ConfLNsType value) {
        this.confLNs = value;
    }

}
